<?php
$whitelist = array(
"admin-panel",
"clients-api",
"cvcore",
"cvcore-message-filtering",
"device-groups-service",
"ding-validator",
"firmware-release-mgmt",
"integrations-services-go",
"motion_verification_and_stop_service",
"notification-service-go",
"ring-api",
"ring-billing",
"ring-masters-ruby",
"ring-media-server",
"ring-nginx-gw",
"ring-oauth-service",
"snapshots-service",
"status-report-reader",
"status-reports-low-battery-notifier",
"status-reports-service"
);
?>
